name: Run main.ts
on:
  workflow_dispatch:
  schedule:
    - cron: "50 19 * * 0" # Run every Sunday at 7:50 PM UTC
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: next-app
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: next-app
      - name: Run main
        run: npm run main
        working-directory: next-app
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          HOUSE_NUMBER: ${{ secrets.HOUSE_NUMBER }}
          POSTCODE: ${{ secrets.POSTCODE }}
          VOODOO_SMS_API_KEY: ${{ secrets.VOODOO_SMS_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: "production"
          DISCORD_NEW_SIGN_UP_CHANNEL_ID: ${{ secrets.DISCORD_NEW_SIGN_UP_CHANNEL_ID }}
