name: Run Bin Scraper on Push

# Trigger the action every time code is pushed to the repository
on:
  push:
    branches:
      - main # This will run the action for pushes to the 'main' branch
      # You can add more branches or use '*' to trigger on all branches:
      # - "*"

jobs:
  run-scraper:
    runs-on: ubuntu-latest # Use a runner with a recent version of Node.js

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Use your preferred Node.js version

      - name: Install dependencies
        run: |
          npm install

      - name: Run Bin Scraper Script
        run: |
          npx ts-node main.ts
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          HOUSE_NUMBER: ${{ secrets.HOUSE_NUMBER }}
          POSTCODE: ${{ secrets.POSTCODE }}
